'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const DB=require('../../server/rewards/db.cjs'),P=require('../../server/rewards/policy.cjs'),Auth=require('../../server/rewards/auth.cjs'),V=require('../../server/rewards/verifier.cjs'),{Keypair}=require('@solana/web3.js');
const fs=require('node:fs'),path=require('node:path');
async function database(){const db=new PGlite();await DB.migrate(db);await db.query("INSERT INTO reward_deployments(id,program,genesis,policy_hash,operations,publisher,verifier,guardian,upgrade_authority) VALUES('d','p','g','h','o','u','v','z','a')");await db.query("INSERT INTO reward_coins(mint,deployment,launcher,intake,treasury,sharing_config,policy_hash,status) VALUES('m','d','l','i','t','s','h','active')");await db.query("INSERT INTO reward_accounts(mint) VALUES('m')");return db;}
test('real PostgreSQL engine migrations, unsigned bounds and conservation constraints',async()=>{const db=await database();try{await DB.migrate(db);await assert.rejects(()=>db.query("UPDATE reward_accounts SET receipts=10 WHERE mint='m'"));await db.query("UPDATE reward_accounts SET receipts=10,unallocated=8,operations_payable=2 WHERE mint='m'");await assert.rejects(()=>db.query("UPDATE reward_accounts SET unallocated=-1 WHERE mint='m'"));assert.equal((await db.query('SELECT count(*) FROM reward_schema_migrations')).rows[0].count,4);}finally{await db.close();}});
test('immutable manifests and atomic reduced settlement release once without another operations charge',async()=>{const db=await database();try{
 await DB.lockPosition(db,'m','w');await db.query("UPDATE reward_positions SET reserved=8 WHERE mint='m'");await db.query("INSERT INTO reward_rounds(mint,round_id,cutoff_slot,cutoff_time,state,root,manifest_hash,manifest,total) VALUES('m',1,1,1,'reserved','r','h','{}',8)");await db.query("INSERT INTO reward_allocations(mint,round_id,leaf_index,wallet,maximum,active,proof,lot_shares,state) VALUES('m',1,0,'w',8,8,'[]','[]','reserved')");
 await assert.rejects(()=>db.query("UPDATE reward_rounds SET total=9 WHERE mint='m'"));await assert.rejects(()=>db.query("UPDATE reward_allocations SET maximum=9,active=9 WHERE mint='m'"));
 const args={mint:'m',round:1,index:0,paid:3,released:5,signature:'sig',slot:2,positionVersion:2,evidence:{reason:'price_recovery'}};await DB.settleAllocation(db,args);await DB.settleAllocation(db,args);await assert.rejects(()=>DB.settleAllocation(db,{...args,signature:'conflict'}));const p=(await db.query('SELECT * FROM reward_positions')).rows[0];assert.equal(p.paid,'3');assert.equal(p.reserved,'0');const a=(await db.query('SELECT * FROM reward_allocations')).rows[0];assert.equal(a.state,'reduced');assert.equal(a.released,'5');assert.equal((await db.query('SELECT operations_payable FROM reward_accounts')).rows[0].operations_payable,'0');
 }finally{await db.close();}});
test('wallet proof binds origin, action and payload, expires and cannot be reused',async()=>{const db=await database();try{const key=Keypair.generate(),wallet=key.publicKey.toBase58(),payload={mint:'m',round:1,index:0},origin='https://reboundpad.fun',action='claim';const c=await Auth.challenge(db,{wallet,payload,origin,action}),proof={id:c.id,signature:V.sign(key,Buffer.from(c.message)).toString('base64')};await assert.rejects(()=>Auth.authenticate(db,{wallet,payload:{...payload,index:1},origin,action,proof}));await Auth.authenticate(db,{wallet,payload,origin,action,proof});await assert.rejects(()=>Auth.authenticate(db,{wallet,payload,origin,action,proof}));assert.equal(Auth.validSignature(Keypair.generate().publicKey.toBase58(),c.message,proof.signature),false);}finally{await db.close();}});

test('database roles isolate raw evidence, reviewed corrections, and deployment controls',async()=>{const db=await database();try{
 await db.exec(fs.readFileSync(path.join(__dirname,'../../scripts/rewards/database-roles.sql'),'utf8'));
 for(const role of ['rebound_api','rebound_indexer','rebound_scheduler','rebound_verifier']){
  await db.query('SET ROLE '+role);
  for(const table of ['reward_deployments','reward_services','reward_link_corrections'])await assert.rejects(()=>db.query('DELETE FROM '+table),/permission denied/);
  await db.query('RESET ROLE');
 }
 await db.query('SET ROLE rebound_scheduler');await assert.rejects(()=>db.query('DELETE FROM reward_raw_blocks'),/permission denied/);await assert.rejects(()=>db.query("UPDATE reward_disqualifications SET kind='sale'"),/permission denied/);await db.query('SELECT * FROM reward_link_corrections');await db.query('RESET ROLE');
 await db.query('SET ROLE rebound_api');await assert.rejects(()=>db.query("UPDATE reward_accounts SET operations_paid=0"),/permission denied/);await db.query('RESET ROLE');
 }finally{await db.close();}});
