'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Keypair}=require('@solana/web3.js'),I=require('../../server/rewards/indexer.cjs');
const key=()=>Keypair.generate().publicKey.toBase58(),mint=key(),a=key(),b=key(),ta=key(),tb=key(),other=key(),coin={mint,intake:key(),sharing_config:key()};
const token='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA';
const move=(from,to,authority=a,amount='1')=>({programId:token,parsed:{type:'transferChecked',info:{source:from,destination:to,authority,mint,tokenAmount:{amount,decimals:6}}}});
function parse(instructions,{toOwner=b,postOwner=toOwner}={}){const tx={transaction:{signatures:['fixture-ordered-exit'],message:{accountKeys:[ta,tb],instructions}},meta:{err:null,innerInstructions:[],preTokenBalances:[{accountIndex:0,mint,owner:a,uiTokenAmount:{amount:'100'}},{accountIndex:1,mint,owner:toOwner,uiTokenAmount:{amount:'100'}}],postTokenBalances:[{accountIndex:0,mint,owner:a,uiTokenAmount:{amount:'100'}},{accountIndex:1,mint,owner:postOwner,uiTokenAmount:{amount:'100'}}]}};return I.parseTransaction(tx,{slot:10,time:10,transactionIndex:0,coins:[coin]});}
test('partial sell/rebuy and unknown venue outflow cannot hide behind zero net changes',()=>{const r=parse([move(ta,tb),move(tb,ta,b)]);assert.ok(r.events.some(e=>e.kind==='transfer_exit'&&e.owner===a));assert.deepEqual(r.holds,[]);});
test('delegated disposition identifies token owner, not delegate or fee payer',()=>{const r=parse([move(ta,tb,other)]);assert.equal(r.events.find(e=>e.kind==='transfer_exit').owner,a);});
test('same-owner account moves preserve history; unsolicited gifts do not ban recipient',()=>{assert.equal(parse([move(ta,tb)],{toOwner:a}).events.filter(e=>e.kind==='transfer_exit').length,0);const r=parse([move(tb,ta,b)]);assert.ok(!r.events.some(e=>e.kind==='transfer_exit'&&e.owner===a));assert.equal(r.events.filter(e=>e.kind==='purchase_candidate').length,0);});
test('burns and controlling-owner reassignment end eligibility',()=>{const r=parse([{programId:token,parsed:{type:'burnChecked',info:{account:ta,mint,authority:other,tokenAmount:{amount:'1',decimals:6}}}},{programId:token,parsed:{type:'setAuthority',info:{account:tb,authorityType:'accountOwner',newAuthority:other}}}],{postOwner:other});assert.ok(r.events.some(e=>e.kind==='burn'&&e.owner===a));assert.ok(r.events.some(e=>e.kind==='owner_change'&&e.owner===b));});
test('missing CPI execution order holds evidence instead of inventing a sale',()=>{const tx={transaction:{signatures:['missing'],message:{accountKeys:[],instructions:[{programId:other}]}},meta:{err:null,innerInstructions:[{index:0,instructions:[move(ta,tb)]}]}};const r=I.parseTransaction(tx,{slot:10,time:10,transactionIndex:0,coins:[coin]});assert.equal(r.events.length,0);assert.ok(r.holds.length);});
