'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite'),{Keypair,SystemProgram}=require('@solana/web3.js'),T=require('../../server/rewards/transport.cjs'),DB=require('../../server/rewards/db.cjs');
test('durable delivery fixture: crash/ambiguous send is not re-broadcast or counted paid; expiry requires a new check',async()=>{
 const db=new PGlite();await DB.migrate(db);const payer=Keypair.generate();let sends=0,height=100,status=null;
 const connection={getLatestBlockhash:async()=>({blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:150}),sendRawTransaction:async()=>{sends++;throw Error('fixture: lost RPC response after submission');},getSignatureStatuses:async()=>({value:[status]}),getBlockHeight:async()=>height};
 const args={db,connection,cfg:{enabled:true},preflight:{ready:true},job:'fixture-payment',payer,instructions:[SystemProgram.transfer({fromPubkey:payer.publicKey,toPubkey:Keypair.generate().publicKey,lamports:1})],readSettlement:async()=>({definitivelyUnsettled:true})};
 try{const first=await T.submit(args);assert.equal(first.state,'uncertain');assert.equal(sends,1);assert.equal((await T.submit(args)).state,'uncertain');assert.equal(sends,1);height=151;assert.equal((await T.submit(args)).state,'retry_requires_fresh_check');assert.equal(sends,1);const rows=(await db.query('SELECT * FROM reward_chain_attempts')).rows;assert.equal(rows.length,1);assert.equal(rows[0].state,'expired');assert.ok(rows[0].transaction_bytes);}finally{await db.close();}
});
test('disabled runtime constructs no signed transaction and sends nothing',async()=>{const db=new PGlite();await DB.migrate(db);try{const result=await T.submit({db,connection:{},cfg:{enabled:false},job:'disabled',instructions:[],context:{},readSettlement:async()=>({definitivelyUnsettled:true})});assert.equal(result.state,'dry-run');assert.equal((await db.query('SELECT count(*) FROM reward_chain_attempts')).rows[0].count,0);}finally{await db.close();}});
