BEGIN;
-- Policy v3.2 (owner decision 2026-09-27): a sale or transfer excludes the sender for good, a purchase counts
-- after 15 minutes, reference price = max(spot, 15-minute TWAP), no spot/TWAP circuit breaker. Generated from
-- server/rewards/policy-v3.cjs (P3.seed checks the stored hash against the code on every start).
INSERT INTO reward_policies(version,hash,canonical,kind) VALUES('rebound-v3.2','67cfe864c2e51485702a145b8d9aac80235621dff1dd7351f1607f90828dabdf','{"accounting":"fifo_lots_proportional_integer","asset":"native-SOL","buybackHardCapSlippageBps":300,"buybackMaxImpactBps":200,"buybackMaxSlippageBps":100,"cutoffLeadSeconds":60,"cycleSeconds":1800,"holdersBps":8500,"kind":"production","laterActivity":"funded_award_survives","lossUnit":"SOL","maturitySeconds":900,"maxObservationGapSeconds":30,"maxPriceAgeSeconds":30,"maxSpotTwapRatioBps":0,"minRealQuoteLamports":"0","otherBps":1500,"permanentExitOnSale":true,"priceScale":"1000000000000000000","priceWindowSeconds":900,"primaryOther":"retain_on_dev_wallet","pumpHolderRewardMode":false,"referencePrice":"max(spot,twap)","rentPolicy":"defer_undeliverable_as_liability","solUsd":{"feedId":"0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d","maxAgeSeconds":30,"maxConfidenceBps":100,"source":"pyth","usedFor":"display_only"},"thirdPartyOther":"buy_and_burn_primary","transferBasis":"none_for_unproven_incoming","usdScale":"1000000000000","venues":["pump-curve","pump-amm"],"version":"rebound-v3.2","walletLinkExclusion":false}','production') ON CONFLICT(version) DO NOTHING;
INSERT INTO reward_policies(version,hash,canonical,kind) VALUES('rebound-v3.2-test','6ea516c17dfa1b28c86a45aee3990c4828d12e3da5001593ef8df70b58433288','{"accounting":"fifo_lots_proportional_integer","asset":"native-SOL","buybackHardCapSlippageBps":300,"buybackMaxImpactBps":200,"buybackMaxSlippageBps":100,"cutoffLeadSeconds":30,"cycleSeconds":120,"holdersBps":8500,"kind":"test","laterActivity":"funded_award_survives","lossUnit":"SOL","maturitySeconds":900,"maxObservationGapSeconds":30,"maxPriceAgeSeconds":30,"maxSpotTwapRatioBps":0,"minRealQuoteLamports":"0","otherBps":1500,"permanentExitOnSale":true,"priceScale":"1000000000000000000","priceWindowSeconds":900,"primaryOther":"retain_on_dev_wallet","pumpHolderRewardMode":false,"referencePrice":"max(spot,twap)","rentPolicy":"defer_undeliverable_as_liability","solUsd":{"feedId":"0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d","maxAgeSeconds":30,"maxConfidenceBps":100,"source":"pyth","usedFor":"display_only"},"thirdPartyOther":"buy_and_burn_primary","transferBasis":"none_for_unproven_incoming","usdScale":"1000000000000","venues":["pump-curve","pump-amm"],"version":"rebound-v3.2-test","walletLinkExclusion":false}','test') ON CONFLICT(version) DO NOTHING;
-- New tokens register under v3.2; every registered token keeps its own policy.
UPDATE reward_platform SET policy_version='rebound-v3.2',config_version=config_version+1,updated_at=now() WHERE namespace='production' AND policy_version IN ('rebound-v3.0','rebound-v3.1');
UPDATE reward_platform SET policy_version='rebound-v3.2-test',config_version=config_version+1,updated_at=now() WHERE namespace='mainnet_test' AND policy_version IN ('rebound-v3.0-test','rebound-v3.1-test');
INSERT INTO reward_schema_migrations(version) VALUES(18);
COMMIT;
