BEGIN;
-- Launchpad without the on-chain program (owner decision 2026-09-27), same rules as the REBOUND token:
--   * every launched token's pump.fun creator is its own creator wallet, generated by the worker; the key is
--     encrypted like the fee-wallet key and never leaves the worker. The launching user signs the creation.
--   * the worker collects the creator fees, splits every collected lamport once 85/15 (the income ledger):
--     85 % pays the token's underwater holders in the same rounds (positions, 15-minute maturity, permanent
--     exit on sale), 15 % buys the REBOUND token on its market and burns it.
--   * a launch may be paired with SOL or with a quote asset pump.fun admits (Global whitelist or its
--     QuoteControl list) — never an arbitrary token; the pair is checked on chain when the launch is prepared.
ALTER TABLE reward_signers DROP CONSTRAINT reward_signers_role_check;
ALTER TABLE reward_signers ADD CONSTRAINT reward_signers_role_check CHECK(role IN ('primary_dev','fee_payer','publisher','verifier','launch_creator'));
CREATE TABLE reward_creator_wallets (
 address text PRIMARY KEY,
 signer uuid NOT NULL REFERENCES reward_signers(id),
 status text NOT NULL DEFAULT 'available' CHECK(status IN ('available','reserved','assigned')),
 attempt_id uuid,
 mint text,
 reserved_at timestamptz,
 collected_at timestamptz,                    -- last creator-fee sweep attempt (throttle; scheduler)
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX reward_creator_wallet_attempt ON reward_creator_wallets(attempt_id) WHERE attempt_id IS NOT NULL;
ALTER TABLE reward_launch_attempts ADD COLUMN creator_wallet text, ADD COLUMN quote_mint text, ADD COLUMN settlement text;
ALTER TABLE reward_coins ADD COLUMN quote_mint text;
ALTER TABLE reward_public_tokens ADD COLUMN quote_mint text, ADD COLUMN quote_symbol text, ADD COLUMN burned_raw numeric, ADD COLUMN burns integer;
-- 15 % of a launched token's fees: buy the REBOUND token, then burn exactly what was bought.
CREATE TABLE reward_burns (
 id uuid PRIMARY KEY,
 mint text NOT NULL REFERENCES reward_coins(mint),
 target_mint text NOT NULL,
 lamports reward_uint NOT NULL,
 bought_raw reward_uint,
 buy_signature text,
 burn_signature text,
 state text NOT NULL DEFAULT 'buying' CHECK(state IN ('buying','bought','burned','failed')),
 reason text,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reward_burns_mint ON reward_burns(mint,created_at);
ALTER TABLE reward_intents DROP CONSTRAINT reward_intents_kind_check;
ALTER TABLE reward_intents ADD CONSTRAINT reward_intents_kind_check CHECK(kind IN ('launch','activation','primary_funding','third_party_credit','round_fund','payout','collection','buyback_purchase','buyback_burn','setup','direct_launch'));
SELECT reward_secure_new_tables();

-- The API never writes creator wallets directly: it can only reserve a free one for a launch attempt and
-- assign that attempt's own wallet to the mint the chain shows. An assigned wallet never returns to the pool
-- (one creator vault per token). Releasing an unused reservation is the scheduler's job, after chain checks.
CREATE FUNCTION reward_reserve_creator_wallet(p_attempt uuid) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE a text; BEGIN
 IF NOT EXISTS(SELECT 1 FROM rebound.reward_launch_attempts WHERE id=p_attempt AND state IN ('draft','awaiting_creation_signature')) THEN RAISE EXCEPTION 'launch attempt not reservable'; END IF;
 SELECT address INTO a FROM rebound.reward_creator_wallets WHERE attempt_id=p_attempt;
 IF a IS NOT NULL THEN RETURN a; END IF;
 UPDATE rebound.reward_creator_wallets SET status='reserved',attempt_id=p_attempt,reserved_at=now()
  WHERE address=(SELECT address FROM rebound.reward_creator_wallets WHERE status='available' ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED) AND status='available'
  RETURNING address INTO a;
 RETURN a;
END $$;
CREATE FUNCTION reward_assign_creator_wallet(p_attempt uuid,p_mint text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE n integer; BEGIN
 UPDATE rebound.reward_creator_wallets w SET status='assigned',mint=p_mint
  FROM rebound.reward_launch_attempts a
  WHERE a.id=p_attempt AND a.mint=p_mint AND a.creator_wallet=w.address AND w.attempt_id=p_attempt AND w.status IN ('reserved','assigned') AND (w.mint IS NULL OR w.mint=p_mint);
 GET DIAGNOSTICS n=ROW_COUNT; RETURN n=1;
END $$;
REVOKE ALL ON FUNCTION reward_reserve_creator_wallet(uuid),reward_assign_creator_wallet(uuid,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION reward_reserve_creator_wallet(uuid),reward_assign_creator_wallet(uuid,text) TO rebound_api;

GRANT SELECT,INSERT,UPDATE ON reward_creator_wallets,reward_burns TO rebound_scheduler;
GRANT SELECT ON reward_creator_wallets,reward_burns TO rebound_indexer,rebound_verifier,rebound_api;
INSERT INTO reward_schema_migrations(version) VALUES(19);
COMMIT;
