/* REBOUND / Solana interface. SOL-denominated holder ledger.
   Address-only wallet access. No signing or transaction-sending method is used. */
(() => {
'use strict';
const E=window.ReboundEngine,F=window.ReboundFixtures,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const STORAGE='rebound.demo.holders.v4';
let state=F.create(),route='explore',tokenId='demo-rbd',filter='all',search='',sort='cap',tradeSide='buy',detailTab='overview';
let launchStep=1,launchDraft={name:'',symbol:'',description:'',website:'',twitter:'',telegram:'',currency:'SOL',taxBps:500,image:null};
let provider=null,connectedAddress=null,providerListeners=[],walletBusy=false;
try{const raw=localStorage.getItem(STORAGE);if(raw){const restored=E.parse(raw);if(restored.version===4&&Array.isArray(restored.tokens)&&restored.tokens.length<=100&&Number.isSafeInteger(restored.now)&&typeof restored.demoBalances?.SOL==='bigint'){for(const t of restored.tokens){E.assertAccounting(t.treasury);E.validateTax(t.taxBps);if(!F.assets[t.currency]||!Array.isArray(t.positions)||t.currency!=='SOL'||t.decimals!==9||typeof t.priceQ!=='bigint'||t.priceQ<=0n)throw Error('Invalid saved demo');}state=restored;}}}catch{state=F.create();}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=9,p=4)=>E.formatUnits(n,d,Math.min(p,d));
const money=v=>v>=1e6?'$'+(v/1e6).toFixed(2)+'M':v>=1e3?'$'+(v/1e3).toFixed(1)+'K':'$'+v.toFixed(0);
const unit=t=>10n**BigInt(t.decimals);
const currentToken=()=>state.tokens.find(t=>t.id===tokenId)||state.tokens[0];
const pos=t=>t.positions.find(p=>p.wallet==='demo-holder');

function save(){try{localStorage.setItem(STORAGE,E.stringify(state));}catch{toast('Browser storage is unavailable or full. Your demo will last only for this session.',true);}}
function toast(text,error=false){const d=document.createElement('div');d.className='toast'+(error?' error':'');d.textContent=text;$('#toasts').append(d);setTimeout(()=>d.remove(),7000);}
function go(hash){if(location.hash==='#'+hash)render();else location.hash=hash;}
function totals(field){const out={SOL:0n};for(const t of state.tokens)out[t.currency]+=t.treasury[field];return out;}
function assetTotals(values,precision=3){return `${fmt(values.SOL,9,precision)} <span class="asset-unit">SOL</span>`;}
function icon(t,large=false){
 const paths={rebound:'<path d="M7 7v11a8 8 0 0 0 16 0V5m-5 5 5-5 5 5"/>',orbit:'<circle cx="16" cy="16" r="7"/><ellipse cx="16" cy="16" rx="14" ry="5" transform="rotate(-35 16 16)"/>',wind:'<path d="M4 11h15a4 4 0 1 0-4-4M4 16h21a4 4 0 1 1-4 4M4 22h8"/>',cat:'<path d="m7 15-1-9 8 5h5l7-5-1 10c4 13-21 14-18-1Z"/><path d="M11 18h1m8 0h1m-7 6 2-2 2 2"/>',drift:'<path d="m4 20 8-10 5 10 6-12 6 12M5 25h23"/>',nimble:'<path d="m18 3-11 17h10l-3 10 12-18H16l2-9Z"/>',mellow:'<circle cx="16" cy="16" r="12"/><path d="M10 13h1m10 0h1M10 19c4 5 8 5 12 0"/>',encore:'<path d="m6 7 12 9L6 25V7Zm13 0v18m7-18v18"/>'};
 const image=typeof t.image==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(t.image)?`<img class="image-token" alt="" src="${esc(t.image)}">`:`<svg viewBox="0 0 32 32" aria-hidden="true">${paths[t.art]||paths.rebound}</svg>`;
 return `<span class="token-icon ${['lime','lilac','blue','peach','mint','pink','yellow'].includes(t.tone)?t.tone:'emerald'} ${large?'large':''}">${image}</span>`;
}
function spark(seed=0,down=false){let y=23;const points=[];for(let x=0;x<=100;x+=4){y=Math.max(3,Math.min(27,y-0.54+Math.sin(x*1.3+seed)*3.8));points.push(`${x},${down?30-y:y}`);}return `<svg class="sparkline ${down?'down':''}" viewBox="0 0 100 30" aria-label="Illustrative price history"><path d="M${points.join(' L')}"/></svg>`;}
function uiIcon(name){
 const shapes={
  compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2.6 5.4L8 16l2.6-5.4L16 8Z"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  wallet:'<path d="M19 7H5a2 2 0 0 1 0-4h13v4M5 7a2 2 0 0 1-2-2v13a2 2 0 0 0 2 2h16V7h-2Z"/><path d="M21 11h-6v5h6M17.5 13.5h.01"/>',
  chart:'<path d="M4 4v16h17M8 15v-4m5 4V7m5 8V4"/>',
  layers:'<path d="m12 3 10 5-10 5L2 8l10-5ZM3 12l9 5 9-5M3 16l9 5 9-5"/>',
  book:'<path d="M4 4h6a3 3 0 0 1 2 1 3 3 0 0 1 2-1h6v15h-6a3 3 0 0 0-2 1 3 3 0 0 0-2-1H4V4Zm8 1v15"/>',
  arrow:'<path d="M5 19 19 5M6 5h13v13"/>',
  arrowRight:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
  spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/>',
  dots:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
  grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
  people:'<circle cx="9" cy="8" r="3"/><path d="M3 20v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m3 9v-3a6 6 0 0 0-2-4"/>',
  bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-8l1-7Z"/>'
 };
 return `<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${shapes[name]||shapes.arrow}</svg>`;
}
function art(){
 const mark='<svg viewBox="0 0 32 28" focusable="false"><use href="#sol-symbol"/></svg>';
 const pieces=[10,26,42,58,75,91,18,82].map((x,i)=>`<span class="sol-fragment fragment-${i}" style="--x:${x}%;--duration:${9+i%4*2}s;--delay:-${i*2.3+1}s;--size:${18+i%3*7}px;--drift:${i%2?-22:24}px;--turn:${i%2?28:-32}deg">${mark}</span>`).join('');
 return `<div class="engine-visual"><div class="engine-top"><span><i class="status-dot"></i> NET FEE ALLOCATION</span><span>SOL</span></div><div class="reward-scene" aria-hidden="true"><div class="reward-guides"></div><div class="reward-rain">${pieces}</div><div class="sol-medallion"><svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" focusable="false"><path d="M7 9v9a9 9 0 0 0 18 0V6M19 11l6-6 5 6"/></svg></div><div class="sol-pool"></div></div><div class="allocation-split"><div class="holder-share"><strong>85<span>%</span></strong><span>Holders</span></div><div class="operations-share"><strong>15<span>%</span></strong><span>Operations</span></div></div><div class="engine-bars" aria-label="85% holders, 15% operations"><i></i><i></i></div><div class="engine-foot">Rewards in SOL. Based on recorded losses and available fees.</div></div>`;
}
function feeBar(){return '<div class="fee-bar" aria-label="85 percent holders, 15 percent operations"><span></span><span></span></div><div class="fee-legend"><span><i></i>85% Holders</span><span><i></i>15% Operations</span></div>';}
function metrics(){return `<div class="stats-row"><div class="stat"><div class="stat-top"><span class="label">Rewards paid</span>${uiIcon('wallet')}</div><strong>${assetTotals(totals('paid'))}</strong><span class="sub">Completed demo payouts</span></div><div class="stat"><div class="stat-top"><span class="label">Holder funds available</span>${uiIcon('layers')}</div><strong>${assetTotals(totals('available'))}</strong><span class="sub">Ready for future reward rounds</span></div><div class="stat"><div class="stat-top"><span class="label">Tokens launched</span>${uiIcon('bolt')}</div><strong>${state.tokens.length.toString().padStart(2,'0')}</strong><span class="sub">Local token launches</span></div><div class="stat"><div class="stat-top"><span class="label">Operations allocation</span>${uiIcon('people')}</div><strong>${assetTotals(totals('operations'))}</strong><span class="sub">15% of net collected fees</span></div></div>`;}
function marketRows(){let tokens=state.tokens.filter(t=>(filter==='all'||(filter==='platform'?t.id==='demo-rbd':t.id!=='demo-rbd'))&&(`${t.name} ${t.symbol} ${t.id}`.toLowerCase().includes(search.toLowerCase())));tokens.sort((a,b)=>sort==='new'?b.createdAt-a.createdAt:sort==='change'?b.change-a.change:(b.marketCap||0)-(a.marketCap||0));return tokens.length?tokens.map((t,i)=>`<tr data-token="${esc(t.id)}" tabindex="0" aria-label="Open ${esc(t.name)} demo token"><td><div class="token-info">${icon(t)}<div><div class="token-name">${esc(t.name)}</div><div class="token-sub">$${esc(t.symbol)} <span>·</span> Trades in ${esc(t.currency)} <span class="tag-inline">${(t.taxBps/100).toFixed(t.taxBps%100?2:0)}% tax</span></div></div></td><td class="numeric">${money(t.marketCap||0)}</td><td class="col-change ${(t.change||0)>=0?'positive':'negative'}">${(t.change||0)>=0?'+':''}${(t.change||0).toFixed(2)}%</td><td class="numeric">${money(t.volume||0)}</td><td class="col-rewards numeric">${fmt(t.treasury.paid,t.decimals,4)} <span>${esc(t.currency)}</span></td><td class="chart-col">${spark(i*3,(t.change||0)<0)}</td><td class="row-arrow">↗</td></tr>`).join(''):'<tr><td colspan="7" class="empty">No tokens match your search.</td></tr>';}
function explore(){
 const spotlight=state.tokens.filter(t=>['demo-rbd','demo-orbit','demo-wind'].includes(t.id));
 return `<section class="hero"><div class="hero-copy"><h1>Launch a token.<br><em>Reward holders.</em></h1><p>85% of net fees goes to holders.<br>15% funds operations. Rewards are paid in SOL.</p><div class="hero-actions"><a href="#launch" class="btn">Launch a token ${uiIcon('arrowRight')}</a><a href="#docs" class="btn ghost">How it works ${uiIcon('arrow')}</a></div><div class="hero-fineprint">${uiIcon('shield')} 85% holders · 15% operations · SOL rewards</div></div>${art()}</section>${metrics()}
 <section class="spotlight-section" aria-label="Featured demo tokens"><div class="section-heading compact"><h2>${uiIcon('spark')} Featured tokens</h2><span class="micro-label">CURATED DEMO TOKENS</span></div><div class="spotlight-grid">${spotlight.map((t,i)=>`<a class="spotlight-card" href="#token/${esc(t.id)}"><div class="spotlight-top"><span class="spotlight-position">0${i+1} / ${['ECOSYSTEM TOKEN','COMMUNITY TOKEN','RECENT LAUNCH'][i]}</span>${uiIcon('arrow')}</div><div class="spotlight-identity">${icon(t)}<div><h3>${esc(t.name)}</h3><span>$${esc(t.symbol)} <span class="spotlight-currency">· Trades in ${esc(t.currency)}</span></span></div><span class="spotlight-change positive">+${t.change.toFixed(2)}%</span></div><div class="spotlight-bottom"><div><span class="micro-label">MARKET CAP</span><strong>${money(t.marketCap||0)}</strong></div>${spark(i*3)}</div></a>`).join('')}</div></section>
 <section class="market-section"><div class="section-heading"><div class="market-heading"><h2>Explore tokens</h2><span class="count-badge">${state.tokens.length}</span></div><span class="demo-data-label"><i class="mini-dot"></i> Demo market data</span></div><div class="toolbar"><div class="tabs" aria-label="Token category"><button data-filter="all" class="${filter==='all'?'active':''}">All tokens</button><button data-filter="community" class="${filter==='community'?'active':''}">Community</button><button data-filter="platform" class="${filter==='platform'?'active':''}">$RBD</button></div><div class="toolbar-right"><label class="search">${uiIcon('search')}<input id="search" placeholder="Search tokens…" aria-label="Search tokens" value="${esc(search)}"><kbd>/</kbd></label><select id="sort" aria-label="Sort tokens"><option value="cap" ${sort==='cap'?'selected':''}>Market cap ↓</option><option value="change" ${sort==='change'?'selected':''}>24h change ↓</option><option value="new" ${sort==='new'?'selected':''}>Newest first</option></select></div></div><div class="table-container"><table class="token-table"><thead><tr><th>Token</th><th>Market cap ↓</th><th>24h change</th><th>24h volume</th><th>Rewards paid</th><th class="chart-col">Price trend</th><th></th></tr></thead><tbody id="market-rows">${marketRows()}</tbody></table></div><div class="table-note"><span>Illustrative prices and charts. Not live market data.</span><span>${state.tokens.length} demo tokens</span></div></section>
 <section class="feature-grid"><div class="feature-card"><div class="feature-icon">${uiIcon('layers')}</div><div><div class="eyebrow">FEE ALLOCATION</div><h3>Where trading fees go</h3><p>85% of net collected fees funds holder rewards. The remaining 15% funds operations.</p>${feeBar()}</div></div><div class="feature-card tinted"><div class="feature-icon">${uiIcon('shield')}</div><div><div class="eyebrow">HOLDER REWARDS</div><h3>Rewards paid in SOL</h3><p>Track available holder funds and completed SOL rewards.</p><a href="#token/demo-rbd" class="arrow-link">View reward details ${uiIcon('arrowRight')}</a></div></div></section>`;
}
function liveNotice(){return connectedAddress?`<div class="live-notice">Connected wallet: ${esc(connectedAddress)} · Read-only connection. All balances and actions below belong to <b>demo-holder</b>, not this wallet.</div>`:'';}
function taxLabels(t){return `<div class="kv"><span>Creator tax · buy / sell</span><strong>${t.taxBps/100}%</strong></div><div class="kv"><span>Demo venue fee</span><strong>1%</strong></div><div class="kv"><span>Combined demo fee</span><strong>${(t.taxBps+100)/100}%</strong></div>`;}
function launchPreview(){const d=launchDraft;return `<aside class="card sticky"><div class="card-title"><h3>Token preview</h3><span class="tag neutral">PREVIEW</span></div>${icon({...d,tone:'emerald',art:'rebound'},true)}<div class="preview-name">${esc(d.name||'Token name')}</div><div class="preview-sub">$${esc(d.symbol||'TOKEN')} · SOL rewards</div><div class="divider"></div>${taxLabels(d)}${feeBar()}<p class="muted mt">Holder rewards cover recorded losses and are paid in SOL. The fee split applies to net collected creator fees.</p></aside>`;}
function launchPage(){let content='';if(launchStep===1)content=`<h3 style="margin-bottom:23px">Token details</h3><label class="upload"><input id="image-input" type="file" accept="image/png,image/jpeg,image/webp" class="hidden"><span class="upload-art">${launchDraft.image?`<img src="${esc(launchDraft.image)}" alt="Token artwork preview">`:'+'}</span><span class="upload-text"><b>${launchDraft.image?'Change artwork':'Add token artwork'}</b><small>PNG, JPG or WebP · cropped to a square · stored locally</small></span></label><div class="input-row"><label class="field"><span>Token name</span><input id="launch-name" data-draft="name" maxlength="32" placeholder="e.g. Second Wind" value="${esc(launchDraft.name)}" autocomplete="off"></label><label class="field"><span>Ticker</span><input id="launch-symbol" data-draft="symbol" maxlength="10" placeholder="e.g. WIND" value="${esc(launchDraft.symbol)}" autocomplete="off"></label></div><label class="field"><span>Description <small>optional</small></span><textarea id="launch-description" data-draft="description" maxlength="500" placeholder="Describe your token and community.">${esc(launchDraft.description)}</textarea></label><label class="field"><span>Website <small>optional</small></span><input type="url" data-draft="website" placeholder="https://your-community.com" value="${esc(launchDraft.website)}"></label><div class="input-row"><label class="field"><span>X / Twitter <small>optional</small></span><input type="url" data-draft="twitter" placeholder="https://x.com/yourtoken" value="${esc(launchDraft.twitter)}"></label><label class="field"><span>Telegram <small>optional</small></span><input type="url" data-draft="telegram" placeholder="https://t.me/yourtoken" value="${esc(launchDraft.telegram)}"></label></div>`;
else if(launchStep===2)content=`<h3 style="margin-bottom:22px">Fees and rewards</h3><label class="field"><span>Trading currency</span></label><div class="option-grid mb"><button data-currency="SOL" class="option ${launchDraft.currency==='SOL'?'active':''}"><h4>◎ SOL</h4><p>Native Solana asset</p></button></div><label class="field"><span>Creator tax <small>same on buys and sells</small></span><div class="input-row"><input id="tax-range" type="range" min="10" max="1000" step="1" value="${launchDraft.taxBps}" aria-label="Creator tax basis points"><input id="tax-number" type="number" min="0.1" max="10" step="0.01" value="${launchDraft.taxBps/100}" aria-label="Creator tax percent"></div><small>0.10%-10.00% · Fixed for this launch. Separate 1% demo venue fee.</small></label><div class="mode-card active"><div class="card-title" style="margin:0"><h4>↗ Holder rewards</h4><span class="tag lime">85% / 15%</span></div><p>85% of net collected fees funds holder rewards; 15% funds operations.</p></div>`;
else content=`<h3 style="margin-bottom:22px">Review your token</h3><div class="notice warning mb">This creates a local demo token only. There is no mint, program deployment, wallet signature, fee payment, or real trading pool.</div><div class="kv"><span>Name / ticker</span><strong>${esc(launchDraft.name)} / ${esc(launchDraft.symbol)}</strong></div><div class="kv"><span>Trading & fee unit</span><strong>${esc(launchDraft.currency)}</strong></div><div class="kv"><span>Creator tax</span><strong>${launchDraft.taxBps/100}% · immutable in the demo</strong></div><div class="kv"><span>Token policy</span><strong>85% holders / 15% operations</strong></div><div class="kv"><span>Initial on-chain supply</span><strong>Not minted</strong></div><div class="divider"></div><div class="notice">Rewards cover recorded losses and depend on available funds. A sale or outgoing transfer ends future rewards. Already-funded claims remain available.</div>`;
return `<div class="page-head"><div><div class="eyebrow">NEW TOKEN / SOLANA CONCEPT</div><h1>Create a token</h1><p>Set the token details and fee policy. Review before creating the demo.</p></div><span class="tag warning">LOCAL SIMULATION</span></div><div class="steps"><span class="${launchStep===1?'active':''}"><b>1</b>Identity</span><span class="${launchStep===2?'active':''}"><b>2</b>Mechanics</span><span class="${launchStep===3?'active':''}"><b>3</b>Review</span></div>${liveNotice()}<div class="two-columns"><section class="card">${content}<div id="launch-error" class="error" role="alert"></div><div class="form-actions"><button class="btn outline" data-action="launch-back">${launchStep===1?'← Explore':'← Back'}</button><button class="btn dark" data-action="launch-next">${launchStep===3?'Create demo token ↗':'Continue →'}</button></div></section>${launchPreview()}</div>`;}
function positionSummary(t,p){const quantity=p.lots.reduce((s,l)=>s+l.quantity,0n)+p.unrecognized,cost=p.lots.reduce((s,l)=>s+l.cost,0n),value=quantity*t.priceQ/E.PRICE_SCALE,s=E.shortfall(p,F.reference(t,state.now));return `<div class="card-title"><h3>Your ${esc(t.symbol)} position</h3><span class="tag neutral">${p.hasOutgoing?'PAYOUTS ENDED':s.reason==='holding-period'?'15 MIN HOLD':'DEMO'}</span></div><div class="recovery-value">${fmt(quantity,6,2)}<small>${esc(t.symbol)}</small></div><div class="kv"><span>Remaining cost basis</span><strong>${fmt(cost,9)} SOL</strong></div><div class="kv"><span>Value at demo quote</span><strong>${fmt(value,9)} SOL</strong></div><div class="kv"><span>Rewards paid</span><strong>${fmt(p.paid,9)} SOL</strong></div><div class="kv"><span>Funded, unpaid</span><strong>${fmt(p.funded-p.paid,9)} SOL</strong></div><button class="btn full mt" data-action="claim" data-id="${esc(t.id)}">Claim SOL rewards</button>${p.hasOutgoing?'<p class="muted mt">An outgoing sale or transfer ended future rewards. Already-funded claims remain available.</p>':''}`;}
function chart(t){const data=[];let y=155;for(let i=0;i<=60;i++){y=Math.max(30,Math.min(160,y-1.7+Math.sin(i*3.21)*7.2));data.push([i*9.3+3,y]);}const line='M'+data.map(p=>p.join(',')).join(' L');return `<svg class="big-chart" viewBox="0 0 620 205" preserveAspectRatio="none" aria-label="Illustrative price chart, not a market feed"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#17795b" stop-opacity=".5"/><stop offset="1" stop-color="#252525" stop-opacity="0"/></linearGradient></defs>${[35,75,115,155].map(y=>`<path d="M0 ${y}H566" stroke="#333333" stroke-dasharray="3 5" stroke-width=".8"/>`).join('')}<path d="${line} L561,180 L3,180 Z" fill="url(#chart-fill)"/><path d="${line}" fill="none" stroke="#9b9b9b" stroke-width="2"/><circle cx="${data.at(-1)[0]}" cy="${data.at(-1)[1]}" r="3" fill="#9b9b9b"/><text x="578" y="38">HIGH</text><text x="578" y="157">LOW</text><text x="5" y="202">00:00</text><text x="143" y="202">06:00</text><text x="284" y="202">12:00</text><text x="425" y="202">18:00</text><text x="546" y="202">24:00</text></svg>`;}
function tradeCard(t){const p=pos(t),qty=p?p.lots.reduce((s,l)=>s+l.quantity,0n)+p.unrecognized:0n;return `<aside class="trade-card"><div class="card-title"><h3>Trade ${esc(t.symbol)}</h3><span class="tag warning">DEMO ONLY</span></div><div class="tabs"><button data-side="buy" class="${tradeSide==='buy'?'active':''}">Buy</button><button data-side="sell" class="${tradeSide==='sell'?'active':''}">Sell</button></div><div class="amount-box"><label for="trade-amount"><span>You ${tradeSide==='buy'?'pay':'sell'}</span><span>Demo balance ${tradeSide==='buy'?fmt(state.demoBalances[t.currency],t.decimals):fmt(qty,6,2)}</span></label><div class="amount-input"><input id="trade-amount" inputmode="decimal" placeholder="0.00" autocomplete="off"><b>${esc(tradeSide==='buy'?t.currency:t.symbol)}</b></div></div><div class="quick-amounts">${(tradeSide==='buy'?['0.1','0.5','1','5']:['100','1000','5000','10000']).map(x=>`<button data-amount="${x}">${x}</button>`).join('')}</div><div class="kv"><span>Estimated receive</span><strong id="trade-receive">-</strong></div>${taxLabels(t)}<div class="kv"><span>Slippage / curve impact</span><strong>Not modeled</strong></div>${tradeSide==='sell'?'<div class="notice danger mt">Selling reduces your demo token balance and returns the quoted SOL.</div>':''}<button class="btn dark full" data-action="trade">Simulate ${tradeSide==='buy'?'buy':'sell'} ↗</button><p class="trade-note">Fixed-price demonstration, not a bonding-curve quote. No signing or fund movement. Gross cost is used as demo entry basis.</p><div class="error" id="trade-error" role="alert"></div></aside>`;}
function feeHistory(t){return `<section class="card bottom-space"><div class="card-title"><h3>Fee receipts</h3><span class="tag neutral">SOL LEDGER</span></div><div class="table-container"><table class="receipt-table"><thead><tr><th>Receipt</th><th>Collected</th><th>Holders</th><th>Operations</th><th>Dust</th></tr></thead><tbody>${[...t.treasury.collections].reverse().map((r,i)=>`<tr><td>#${t.treasury.collections.length-i}</td><td>${fmt(r.amount,9,9)}</td><td>${fmt(r.split.holders,9,9)}</td><td>${fmt(r.split.operations,9,9)}</td><td>${fmt(r.split.dust,9,9)}</td></tr>`).join('')||'<tr><td colspan="5">No collected fees yet.</td></tr>'}</tbody></table></div><p class="muted mt">Amounts in SOL. Allocated holder funds are separate from completed payouts.</p></section>`;}
function tokenPage(){const t=currentToken(),p=pos(t);return `<a href="#explore" class="back">← All tokens</a><div class="token-head"><div class="token-head-left">${icon(t,true)}<div><h1>${esc(t.name)}</h1><p>$${esc(t.symbol)} <span>·</span> SOL rewards <span class="tag-inline">85 / 15 fee split</span></p></div></div><button class="btn outline small" data-action="copy-token">Copy demo link ↗</button></div>${liveNotice()}<div class="token-layout"><section class="chart-card"><div class="chart-top"><div><span class="muted">Illustrative market cap</span><div class="chart-value">${money(t.marketCap||0)}</div><span class="${t.change>=0?'positive':'negative'}">${t.change>=0?'+':''}${(t.change||0).toFixed(2)}% <span class="muted">sample · past 24h</span></span></div><span class="tag neutral">DEMO</span></div>${chart(t)}<div class="chart-foot"><span>ILLUSTRATIVE CHART</span><span>Demo quote: ${fmt(t.priceQ*1000000n/E.PRICE_SCALE,9,9)} SOL / token</span></div></section>${tradeCard(t)}</div><div class="section-tabs"><button data-detail-tab="overview" class="${detailTab==='overview'?'active':''}">Overview</button><button data-detail-tab="fees" class="${detailTab==='fees'?'active':''}">Fee receipts</button><button data-detail-tab="trades" class="${detailTab==='trades'?'active':''}">Demo trades</button></div>${detailTab==='trades'?tradeHistory(t):detailTab==='fees'?feeHistory(t):`<div class="token-detail-grid"><section class="card">${p?positionSummary(t,p):'<h3>No demo position yet.</h3><p class="muted mt">Make a simulated buy to create a position.</p>'}</section><section class="card"><div class="card-title"><h3>Fee allocation</h3><span class="tag neutral">85 / 15</span></div><div class="recovery-value">${fmt(t.treasury.available,9)}<small>SOL</small></div><p class="muted">Available for holder rewards</p><div class="kv"><span>Funded, unpaid</span><strong>${fmt(t.treasury.reserved,9)} SOL</strong></div><div class="kv"><span>Operations</span><strong>${fmt(t.treasury.operations,9)} SOL</strong></div>${feeBar()}<details class="mt demo-controls"><summary>Demo controls</summary><div class="controls-row"><button class="btn small" data-action="fund" data-id="${esc(t.id)}">Fund holder round</button><button class="btn outline small" data-action="advance-15">Advance 15 min</button><button class="btn outline small" data-action="advance-10">Advance 10 min</button></div><p class="muted mt">Purchases mature after 15 minutes. Funded rounds have a 10-minute wait.</p></details></section></div>`}<div class="notice mt bottom-space">Local simulation. No real trades or SOL transfers occur.</div>`;}
function tradeHistory(t){return `<section class="card bottom-space"><div class="card-title"><h3>Simulated trades</h3><span class="tag neutral">NOT TRANSACTIONS</span></div><table class="receipt-table"><thead><tr><th>Side</th><th>Actor</th><th>Quote amount</th><th>Tokens</th></tr></thead><tbody>${[...t.trades].reverse().map(x=>`<tr><td class="${x.side==='buy'?'positive':'negative'}">${esc(x.side)}</td><td>${esc(x.wallet)}</td><td>${fmt(x.quoteAmount??x.amount,t.decimals)} ${esc(t.currency)}</td><td>${fmt(x.quantity,6,2)}</td></tr>`).join('')||'<tr><td colspan="4">No local trades yet.</td></tr>'}</tbody></table></section>`;}
function portfolio(){const held=state.tokens.filter(t=>pos(t));return `<div class="page-head"><div><h1>Your portfolio</h1><p>Token balances and SOL rewards.</p></div></div>${liveNotice()}<div class="notice mb">Demo account. Paper funds: ${fmt(state.demoBalances.SOL)} SOL. Real wallet balances are not fetched.</div><div class="portfolio-list">${held.map(t=>`<section class="card portfolio-item"><div class="portfolio-item-head"><div class="token-info">${icon(t)}<h3>${esc(t.name)}</h3></div><a href="#token/${esc(t.id)}" class="btn outline small">View token ↗</a></div>${positionSummary(t,pos(t))}</section>`).join('')||'<div class="empty">No demo positions. Explore a token to simulate a purchase.</div>'}</div>`;}
function analytics(){return `<div class="page-head"><div><h1>Treasury activity</h1><p>Holder funds, completed payouts, and operations.</p></div></div>${metrics()}<section class="card bottom-space"><div class="card-title"><h3>Fee allocation</h3><span class="tag neutral">85 / 15</span></div>${feeBar()}<div class="table-container mt"><table class="receipt-table"><thead><tr><th>Token</th><th>Collected SOL</th><th>Available SOL</th><th>Paid SOL</th><th>Operations SOL</th></tr></thead><tbody>${state.tokens.map(t=>`<tr><td><a href="#token/${esc(t.id)}">${esc(t.symbol)} ↗</a></td><td>${fmt(t.treasury.collected,9)}</td><td>${fmt(t.treasury.available,9)}</td><td>${fmt(t.treasury.paid,9)}</td><td>${fmt(t.treasury.operations,9)}</td></tr>`).join('')}</tbody></table></div></section>`;}

function docs(){return `<section class="docs"><div class="page-head"><div><h1>How REBOUND works</h1><p>85% holders. 15% operations. Rewards paid in SOL.</p></div></div><div class="docs-grid"><article class="card"><h3>Fee allocation</h3><p>85% of net collected creator fees funds holder rewards. The remaining 15% funds operations. This split applies to collected fees, not total trading volume.</p>${feeBar()}</article><article class="card"><h3>Holder rewards</h3><p>Rewards cover recorded losses, up to the remaining shortfall and available funds. Recognized purchases mature after 15 minutes. The reference value uses the higher of spot and the 15-minute average.</p></article><article class="card"><h3>Claiming SOL</h3><p>Funded rounds wait 10 minutes before claims open. Funded rewards immediately reduce the next loss calculation. A sale or outgoing transfer ends future rewards, but already-funded claims remain available.</p></article><article class="card"><h3>Prototype status</h3><p>Trades, balances, prices, and rewards are simulated. There is no live Pump.fun integration, deployed token, or real SOL transfer. Wallet connection shares a public address only.</p><p class="mt">USDC is reference metadata only. Trading and rewards use SOL.</p></article></div></section>`;}
function render(){const parts=location.hash.slice(1).split('/');route=parts[0]||'explore';tokenId=parts[1]||tokenId;const pages={explore,launch:launchPage,portfolio,analytics,docs,token:tokenPage};if(!pages[route])route='explore';$('#main').innerHTML=pages[route]();$$('[data-nav]').forEach(a=>{const active=a.dataset.nav===(route==='token'?'explore':route);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.body.dataset.route=route;updateWalletButton();document.title=(route==='token'?currentToken().name+' · ':route==='explore'?'':route.charAt(0).toUpperCase()+route.slice(1)+' · ')+'REBOUND';}
function modal(html){$('#dialog-body').innerHTML='<div class="dialog-content">'+html+'</div>';if(!$('#dialog').open)$('#dialog').showModal();}
function closeDialog(){$('#dialog').close();}
function head(title){return `<div class="dialog-head"><h2>${esc(title)}</h2><button class="close" data-action="close" aria-label="Close dialog">×</button></div>`;}
function updateWalletButton(){const b=$('.wallet-button');b.innerHTML=connectedAddress?esc(connectedAddress.slice(0,4)+'…'+connectedAddress.slice(-4))+' <span>↗</span>':uiIcon('wallet')+'Connect wallet';}
function walletModal(){if(connectedAddress){modal(head('Wallet connected')+`<p>Your wallet is connected for address display only.</p><div class="code">${esc(connectedAddress)}</div><button class="btn full mt" data-action="disconnect">Disconnect</button>`);return;}const ph=!!window.phantom?.solana,sf=!!window.solflare;modal(`<div class="wallet-connect"><section class="wallet-choices"><div class="dialog-head"><h2>Connect a wallet</h2><button class="close" data-action="close" aria-label="Close dialog">×</button></div><p class="wallet-network">SOLANA</p><button class="wallet-pick" data-wallet="phantom"><span class="wallet-symbol">${uiIcon('wallet')}</span><span><b>Phantom</b><small>${ph?'Installed':'Solana wallet'}</small></span><span class="wallet-pick-arrow">↗</span></button><button class="wallet-pick" data-wallet="solflare"><span class="wallet-symbol">${uiIcon('spark')}</span><span><b>Solflare</b><small>${sf?'Installed':'Solana wallet'}</small></span><span class="wallet-pick-arrow">↗</span></button><p class="wallet-safety">Address only. No signatures or transactions.</p><button class="wallet-skip" data-action="close">Continue in demo mode</button></section><aside class="wallet-about"><div class="wallet-illustration">${uiIcon('wallet')}</div><h3>New to wallets?</h3><p>A Solana wallet holds your tokens and connects you to apps.</p><div class="wallet-get-links"><a href="https://phantom.com/" target="_blank" rel="noopener noreferrer">Get Phantom ↗</a><a href="https://solflare.com/" target="_blank" rel="noopener noreferrer">Get Solflare ↗</a></div><p class="wallet-about-note">Your demo funds stay separate from your wallet.</p></aside></div>`);}
function detach(){for(const [event,fn]of providerListeners)provider?.removeListener?.(event,fn);providerListeners=[];}
async function connectWallet(which){if(walletBusy)return;const candidate=which==='phantom'?window.phantom?.solana:window.solflare;if(!candidate){toast(`${which==='phantom'?'Phantom':'Solflare'} was not detected. Open the app on localhost in a browser with that wallet installed.`,true);return;}walletBusy=true;try{const result=await candidate.connect();const address=(result?.publicKey||candidate.publicKey)?.toString();if(!address||!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address))throw Error('Wallet did not return a valid Solana public address.');detach();provider=candidate;connectedAddress=address;const disconnected=()=>{detach();provider=null;connectedAddress=null;render();};const changed=key=>{const address=key?.toString();connectedAddress=address&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address)?address:null;render();};if(provider.on){provider.on('disconnect',disconnected);provider.on('accountChanged',changed);providerListeners=[['disconnect',disconnected],['accountChanged',changed]];}closeDialog();render();toast('Wallet connected read-only. Demo balances are separate.');}catch(err){toast(err?.code===4001?'Wallet connection was declined. No changes were made.':err.message||'Could not connect wallet.',true);}finally{walletBusy=false;}}
async function disconnect(){const old=provider;detach();provider=null;connectedAddress=null;try{await old?.disconnect?.();}catch{}closeDialog();render();toast('Wallet disconnected.');}
function validateDraft(){const d=launchDraft;E.invariant(d.currency==='SOL','Trading and fee accounting use SOL');d.name=d.name.trim();d.symbol=d.symbol.trim().toUpperCase();E.invariant(d.name.length>=2&&d.name.length<=32,'Use a token name with 2-32 characters.');E.invariant(/^[A-Z0-9]{2,10}$/.test(d.symbol),'Ticker must have 2-10 letters or digits.');for(const key of ['website','twitter','telegram'])if(d[key]){let url;try{url=new URL(d[key]);}catch{throw Error('Enter a valid HTTPS '+key+' URL.');}E.invariant(url.protocol==='https:','Use HTTPS URLs only.');}E.validateTax(d.taxBps);}
function launchNext(){try{if(launchStep===2){const input=$('#tax-number').value;E.invariant(/^(0|[1-9]\d*)(\.\d{1,2})?$/.test(input),'Tax must have at most two decimal places.');const bps=Number(E.parseUnits(input,2));E.validateTax(bps);launchDraft.taxBps=bps;}validateDraft();if(launchStep<3){launchStep++;render();window.scrollTo(0,0);return;}E.invariant(state.tokens.length<100,'The local demo is limited to 100 tokens.');const id='demo-'+(crypto.randomUUID?crypto.randomUUID().slice(0,8):Date.now().toString(36));const t=F.token({...launchDraft,id,tone:'emerald',art:'rebound',tag:'Your launch',marketCap:0,volume:0,change:0,blank:true},state.now);state.tokens.unshift(t);save();launchStep=1;launchDraft={name:'',symbol:'',description:'',website:'',twitter:'',telegram:'',currency:'SOL',taxBps:500,image:null};tradeSide='buy';detailTab='overview';go('token/'+id);toast('Demo token created. No on-chain mint or pool exists.');}catch(e){$('#launch-error').textContent=e.message;}}
function quote(t,amount,side){const tax=BigInt(t.taxBps),base=100n;if(side==='buy'){const creatorFee=amount*tax/10000n,venueFee=amount*base/10000n,net=amount-creatorFee-venueFee;return {quantity:net*E.PRICE_SCALE/t.priceQ,received:net*E.PRICE_SCALE/t.priceQ,creatorFee,venueFee};}const gross=amount*t.priceQ/E.PRICE_SCALE,creatorFee=gross*tax/10000n,venueFee=gross*base/10000n;return {quantity:amount,received:gross-creatorFee-venueFee,creatorFee,venueFee};}
function updateQuote(){const t=currentToken(),out=$('#trade-receive');if(!out)return;try{const v=$('#trade-amount').value.trim();if(!v){out.textContent='-';return;}const a=E.parseUnits(v,tradeSide==='buy'?t.decimals:6),q=quote(t,a,tradeSide);out.textContent=fmt(q.received,tradeSide==='buy'?6:t.decimals,4)+' '+(tradeSide==='buy'?t.symbol:t.currency);}catch{out.textContent='Invalid amount';}}
function simulateTrade(){const t=currentToken();try{const amount=E.parseUnits($('#trade-amount').value.trim(),tradeSide==='buy'?t.decimals:6);E.invariant(amount>0n,'Enter an amount greater than zero.');const q=quote(t,amount,tradeSide);E.invariant(q.received>0n,'Amount is too small for this demo quote.');let p=pos(t);if(tradeSide==='buy')E.invariant(amount<=state.demoBalances[t.currency],'Insufficient paper funds. Reset the demo to restore balances.');else{E.invariant(!!p,'No demo position to sell.');E.invariant(amount<=p.lots.reduce((s,l)=>s+l.quantity,0n)+p.unrecognized,'Insufficient demo tokens.');}
 const execute=()=>{try{const id='demo-trade-'+state.tokens.reduce((s,t)=>s+t.trades.length,0)+'-'+state.now;if(!p){p=E.newPosition('demo-holder');t.positions.push(p);}if(tradeSide==='buy'){state.demoBalances[t.currency]-=amount;E.purchase(p,{id,quantity:q.quantity,officialCost:amount,at:state.now});}else{E.outgoing(p,amount);state.demoBalances[t.currency]+=q.received;}E.collect(t.treasury,id,q.creatorFee,state.now);t.trades.push({id,side:tradeSide,wallet:'demo-holder',amount,quoteAmount:tradeSide==='buy'?amount:q.received,quantity:q.quantity,at:state.now,simulated:true});save();closeDialog();render();toast(tradeSide==='buy'?'Demo buy recorded. This purchase matures after 15 demo minutes.':'Demo sale recorded. Future rewards ended; already-funded claims remain available.');}catch(e){toast(e.message,true);}};
 if(tradeSide==='sell'){modal(head('Confirm a demo sale')+'<p>Selling ends future holder rewards for this token. Already-funded claims remain available. No real transaction occurs.</p><button id="confirm-trade" class="btn dark full">Confirm simulated sale</button>');$('#confirm-trade').onclick=execute;}else execute();
}catch(e){$('#trade-error').textContent=e.message;}}


function advance(ms){state.now+=ms;save();render();toast(`Demo clock advanced ${ms/60000>=60?ms/3600000+' hours':ms/60000+' minutes'}. No real-world timer was changed.`);}
function plain(obj){return JSON.parse(JSON.stringify(obj,(_,x)=>typeof x==='bigint'?x.toString():x));}

function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copyToken(){const text=location.href;try{await navigator.clipboard.writeText(text);toast('Demo link copied. Local file links are usable only on this computer.');}catch{modal(head('Your demo token link')+'<p>A local link is not a public launch URL.</p><div class="code">'+esc(text)+'</div>');}}
async function upload(file){try{E.invariant(file&&['image/png','image/jpeg','image/webp'].includes(file.type),'Choose a PNG, JPEG, or WebP image.');E.invariant(file.size<=5*1024*1024,'Image must be under 5 MB.');const bitmap=await createImageBitmap(file);E.invariant(bitmap.width>0&&bitmap.height>0,'Invalid image dimensions');const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d'),side=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);bitmap.close();const data=canvas.toDataURL('image/webp',.8);E.invariant(data.length<=131072,'Image is too large after resizing.');launchDraft.image=data;render();}catch(e){toast(e.message||'Unable to read image.',true);}}
function fundToken(id){try{const t=state.tokens.find(t=>t.id===id);const r=E.fund(t.treasury,t.positions,F.reference(t,state.now),state.now);save();render();toast(`Round #${r.id} funded. Advance 10 demo minutes to claim.`);}catch(e){toast(e.message,true);}}
function claimToken(id){try{const t=state.tokens.find(t=>t.id===id);let total=0n;for(const r of t.treasury.rounds){if(r.cancelled||r.claimableAt>state.now)continue;const a=r.allocations.find(a=>a.wallet==='demo-holder'&&!a.paid);if(a)total+=E.claim(t.treasury,t.positions,r.id,'demo-holder',state.now);}E.invariant(total>0n,'No rewards ready to claim. Fund a round and advance 10 demo minutes.');state.demoBalances.SOL+=total;save();render();toast(`${fmt(total)} SOL added to demo funds.`);}catch(e){toast(e.message,true);}}
const actions={menu:()=>modal(head('Explore REBOUND')+'<nav class="mobile-nav" aria-label="Mobile navigation">'+[['explore','Explore tokens'],['launch','Launch a token'],['portfolio','Your portfolio'],['analytics','Analytics'],['docs','Documentation']].map(([url,name])=>'<a href="#'+url+'" data-action="close">'+name+'<span>↗</span></a>').join('')+'</nav>'),wallet:walletModal,close:closeDialog,disconnect,'launch-next':launchNext,'launch-back':()=>{if(launchStep===1)go('explore');else{launchStep--;render();}},trade:simulateTrade,fund:el=>fundToken(el.dataset.id),claim:el=>claimToken(el.dataset.id),'advance-15':()=>advance(900000),'advance-10':()=>advance(600000),'copy-token':copyToken,reset:()=>{modal(head('Reset the local demo?')+'<p>This clears simulated tokens and trades in this browser. It does not affect a real wallet.</p><button id="confirm-reset" class="btn dark full">Reset demo</button>');$('#confirm-reset').onclick=()=>{state=F.create();save();filter='all';search='';sort='cap';closeDialog();go('explore');render();toast('Demo reset.');};}};

document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-token],[data-filter],[data-side],[data-amount],[data-wallet],[data-currency],[data-detail-tab]');if(!el)return;try{if(el.dataset.action){actions[el.dataset.action]?.(el);return;}if(el.dataset.token){tradeSide='buy';detailTab='overview';go('token/'+el.dataset.token);}else if(el.dataset.filter){filter=el.dataset.filter;render();}else if(el.dataset.side){tradeSide=el.dataset.side;render();}else if(el.dataset.amount){$('#trade-amount').value=el.dataset.amount;updateQuote();}else if(el.dataset.wallet){connectWallet(el.dataset.wallet);}else if(el.dataset.currency){E.invariant(el.dataset.currency==='SOL','Trading and fee accounting use SOL');launchDraft.currency='SOL';render();}else if(el.dataset.detailTab){detailTab=el.dataset.detailTab;render();}}catch(err){toast(err.message,true);}});
document.addEventListener('input',e=>{const el=e.target;if(el.id==='search'){search=el.value;$('#market-rows').innerHTML=marketRows();}if(el.id==='trade-amount')updateQuote();if(el.dataset.draft){launchDraft[el.dataset.draft]=el.value;const name=$('.preview-name'),sub=$('.preview-sub');if(name)name.textContent=launchDraft.name||'Token name';if(sub)sub.textContent='$'+(launchDraft.symbol.toUpperCase()||'TOKEN')+' · '+'Trades in '+launchDraft.currency;}if(el.id==='tax-range'){launchDraft.taxBps=Number(el.value);$('#tax-number').value=launchDraft.taxBps/100;const prev=$('.sticky');if(prev)prev.outerHTML=launchPreview();}if(el.id==='tax-number'){const n=Number(el.value),bps=Math.round(n*100);if(Number.isFinite(n)&&bps>=10&&bps<=1000&&Math.abs(n*100-bps)<1e-7){launchDraft.taxBps=bps;$('#tax-range').value=bps;$('.sticky').outerHTML=launchPreview();$('#launch-error').textContent='';}else{$('#launch-error').textContent='Tax must be 0.10%-10.00%, with at most two decimals.';}}});
document.addEventListener('change',e=>{if(e.target.id==='sort'){sort=e.target.value;$('#market-rows').innerHTML=marketRows();}if(e.target.id==='image-input')upload(e.target.files[0]);});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)&&!e.target.isContentEditable&&!$('#dialog').open&&$('#search')){e.preventDefault();$('#search').focus();return;}if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-token]')){e.preventDefault();go('token/'+e.target.dataset.token);}});
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))closeDialog();});
window.addEventListener('hashchange',()=>{render();window.scrollTo({top:0,behavior:'instant'});});
Object.defineProperty(window,'ReboundDemo',{value:Object.freeze({inspect:()=>E.parse(E.stringify(state)),quote,version:'0.5.0'}),writable:false});
render();
})();
