/* Browser bundle: wallet-signed launches and public rewards data only. */
const {Keypair,Transaction}=require('@solana/web3.js');
const endpoint='/.netlify/functions/rewards';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sol=n=>{if(n==null)return 'Unavailable';const v=BigInt(n),s=String(v%1000000000n).padStart(9,'0').replace(/0+$/,'');return String(v/1000000000n)+(s?'.'+s:'')+' SOL';};
const tokens=(n,d)=>{if(n==null||!Number.isInteger(d)||d<0||d>18)return 'Unavailable';const scale=10n**BigInt(d),value=BigInt(n),fraction=String(value%scale).padStart(d,'0').replace(/0+$/,'');return String(value/scale)+(fraction?'.'+fraction:'');};
const b64=bytes=>{let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s);};
const raw=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const link=(sig,label='View transaction')=>sig?'<a class="text-link" href="https://solscan.io/tx/'+esc(sig)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+' ↗</a>':'';
async function api(action,query={},body,signal){const r=await fetch(endpoint+'?'+new URLSearchParams({action,...query}),{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store',signal});if(!r.headers.get('content-type')?.includes('application/json'))throw Error('Rewards need the Netlify backend. This host currently serves the website only.');const data=await r.json();if(!r.ok)throw Error(data.message||'Rewards service unavailable');return data;}
async function signed(wallet,action,payload){if(!wallet.address)throw Error('Connect your wallet first.');const address=wallet.address,c=await api('challenge',{}, {wallet:address,action,payload});const signature=await wallet.signMessage(c.message);return api(action,{}, {wallet:address,payload,proof:{id:c.id,signature:b64(signature)}});}
const labels={eligible:'Eligible with unrecovered loss',no_remaining_loss:'No remaining loss',disqualified:'Disqualified',awaiting_maturity:'Awaiting 30-minute holding period',hold:'Held for verification',held:'Held for verification',reserved:'Reserved · fresh check pending',reduced:'Paid a reduced amount',canceled:'Canceled · funds released',paid:'Paid',indexing:'Indexing',active:'Active',blocked:'Blocked',verifying:'Verifying launch',preparing:'Preparing launch'};
const policy='<p>85% of collected creator fees belongs to eligible holders; 15% belongs to platform operations. Trading volume and total Pump fees are different amounts.</p><p>Purchases mature after 30 minutes. A sale, outgoing transfer to another owner, burn, or custody/liquidity exit ends future rewards for that coin. Gifts create no qualifying cost. Each payment requires a fresh check.</p><p>Remaining loss = max(0, qualifying cost − reference value − paid compensation − active reservations). A round distributes min(available holder funds, total remaining loss), proportionally to each remaining loss. Prices use the higher of valid spot and a complete 30-minute time average.</p>';
let health=null,mintKey=null,launchBusy=false;
function allocationRows(rows){return rows.map(a=>'<tr><td>'+esc(a.round_id)+'</td><td>'+esc(labels[a.state]||a.state)+'</td><td>'+sol(a.maximum)+'</td><td>'+sol(a.active)+'</td><td>'+sol(a.paid)+'</td><td>'+sol(a.released)+'</td><td>'+link(a.settlement_signature)+(BigInt(a.active)>0n?'<button class="btn outline small" data-reward-claim="'+esc(a.mint)+'" data-round="'+esc(a.round_id)+'" data-index="'+esc(a.leaf_index)+'">Recheck & deliver</button>':'')+'</td></tr>').join('');}
function table(rows){return rows.length?'<div class="table-container"><table class="token-table"><thead><tr><th>Round</th><th>Status</th><th>Original maximum</th><th>Active reservation</th><th>Paid</th><th>Released</th><th>Evidence</th></tr></thead><tbody>'+allocationRows(rows)+'</tbody></table></div>':'<p>No conditional allocations have been verified for this position.</p>';}
function mountLaunch(host,wallet,toast){
 host.innerHTML='<h2>Launch a SOL-paired coin</h2><p>Your connected wallet creates the coin and approves its fee setup. Each mint has its own treasury. The initial creator address protects the route before the first trade.</p><form id="rewards-launch-form"><label>Token name<input name="name" required maxlength="32"></label><label>Symbol<input name="symbol" required maxlength="10"></label><label>Description<textarea name="description" maxlength="2000"></textarea></label><label>Token image<input name="image" type="file" accept="image/png,image/jpeg" required></label><p>Setup deposit: 0.05 SOL for fee-configuration rent, separate from creator-fee income. Pump creation, network fees, and account rent are additional wallet-funded launch costs.</p><button class="btn" '+(!health.launchesEnabled?'disabled':'')+'>Create token & configure fees</button><button class="btn outline" type="button" id="rewards-resume" '+(!health.launchesEnabled?'disabled':'')+'>Resume my launch</button></form><div id="rewards-launch-status" role="status">'+(!health.launchesEnabled?'Launches remain disabled until the deployment and verification checks are complete.':'')+'</div>';
 async function progress(attempt){const status=host.querySelector('#rewards-launch-status');for(let step=0;step<8;step++){const next=await signed(wallet,'launch-next',{attempt});if(!host.isConnected)return;if(next.state==='confirming'){status.innerHTML='Waiting for finalization. '+link(next.signature)+'<p>Use Resume my launch after confirmation.</p>';return;}if(next.state==='active'){status.innerHTML='Fee routing verified. <a href="#token/'+esc(next.mint)+'">View your token →</a>';mintKey=null;return;}status.textContent='Wallet approval: '+next.step+'. Review the transaction details in your wallet.';const tx=Transaction.from(raw(next.transaction));if(next.step==='create'){if(!mintKey||mintKey.publicKey.toBase58()!==next.mint)throw Error('This uncreated mint key is no longer in this browser. Start a new launch; no treasury key is needed.');tx.partialSign(mintKey);}const signedTx=await wallet.signTransaction(tx);const result=await signed(wallet,'launch-submit',{attempt,transaction:b64(signedTx.serialize())});status.innerHTML='Submitted '+esc(next.step)+'. '+link(result.signature)+'<p>Wait for finalization, then select Resume my launch.</p>';return;}}
 host.querySelector('form').onsubmit=async event=>{event.preventDefault();if(launchBusy)return;launchBusy=true;try{const form=new FormData(event.target),file=form.get('image');if(file.size>2000000)throw Error('Choose an image smaller than 2 MB.');const metadata=await signed(wallet,'metadata-upload',{name:form.get('name'),symbol:form.get('symbol'),description:form.get('description'),imageBase64:b64(new Uint8Array(await file.arrayBuffer()))});mintKey=Keypair.generate();const prepared=await signed(wallet,'launch-prepare',{mint:mintKey.publicKey.toBase58(),metadataHash:metadata.hash});sessionStorage.setItem('rebound-launch-'+wallet.address,prepared.attempt);await progress(prepared.attempt);}catch(e){toast(e.message);}finally{launchBusy=false;}};
 host.querySelector('#rewards-resume').onclick=async()=>{if(launchBusy)return;launchBusy=true;try{const attempt=sessionStorage.getItem('rebound-launch-'+wallet.address);if(!attempt)throw Error('No saved launch attempt for this wallet.');await progress(attempt);}catch(e){toast(e.message);}finally{launchBusy=false;}};
}
async function mount({route,mint,wallet,toast,signal}){
 const host=document.querySelector('#rewards-summary');if(!host)return;
 try{
  health=await api('health',{},null,signal);if(!host.isConnected)return;
  host.innerHTML='<span class="tag neutral">'+(health.transfersEnabled?'FRESH CHECK REQUIRED':'PAYMENTS DISABLED')+'</span><h2>Creator fees & conditional rewards</h2>'+policy+'<p>Automatic cycles start every 30 minutes. '+(health.nextCycle?'Next scheduled initiation: '+new Date(health.nextCycle*1000).toLocaleString()+'.':'')+'</p><p>'+esc(health.reason||'Current mode: '+health.state.replaceAll('_',' '))+'</p>';
  if(health.operations)host.innerHTML+='<p class="live-caption">Operations wallet: <span class="live-address">'+esc(health.operations)+'</span></p>';
  if(health.checkpoint)host.innerHTML+='<p>History checked through finalized slot '+esc(health.checkpoint.through_slot)+'. '+(health.checkpoint.complete?'':'Indexing delayed; payouts held.')+'</p>';
  if(route==='launch'){const launch=document.querySelector('#rewards-launch');if(launch)mountLaunch(launch,wallet,toast);}
  if(health.coins?.length)host.innerHTML+='<div class="live-token-links">'+health.coins.map(c=>'<a class="btn outline small" href="#token/'+esc(c.mint)+'">'+esc(c.mint.slice(0,6))+'… · '+esc(c.status)+'</a>').join('')+'</div>';
  if(!mint||!health.coins?.some(c=>c.mint===mint))return;
  const data=await api('coin',{mint},null,signal);if(!host.isConnected)return;const c=data.coin;
  host.innerHTML+='<h3>'+esc(labels[c.status]||c.status)+'</h3><p class="live-address">Treasury: '+esc(c.treasury)+'</p><div class="live-metrics"><div><span>Collected creator fees</span><strong>'+sol(c.receipts)+'</strong></div><div><span>Unallocated holder reserve</span><strong>'+sol(c.unallocated)+'</strong></div><div><span>Conditional reservations</span><strong>'+sol(c.reserved)+'</strong></div><div><span>Holder payments</span><strong>'+sol(c.paid)+'</strong></div><div><span>Operations payable</span><strong>'+sol(c.operations_payable)+'</strong></div><div><span>Operations paid</span><strong>'+sol(c.operations_paid)+'</strong></div></div>'+(c.blocked_reason?'<p>Waiting: '+esc(c.blocked_reason.replaceAll('_',' '))+'</p>':'');
  if(wallet.address){const personal=await api('wallet',{mint,wallet:wallet.address},null,signal);if(!host.isConnected)return;const p=personal.position.view;
   host.innerHTML+='<h3>Your position · '+esc(personal.disqualification?'Disqualified':labels[p.outcome]||p.outcome)+'</h3><p>'+esc((p.reason||'').replaceAll('_',' '))+'</p><div class="live-metrics"><div><span>Recognized cost</span><strong>'+sol(p.cost)+'</strong></div><div><span>Reference value</span><strong>'+sol(p.value)+'</strong></div><div><span>Remaining loss</span><strong>'+sol(p.loss)+'</strong></div></div><p>Latest complete check: '+(personal.position.checked_time?new Date(Number(personal.position.checked_time)*1000).toLocaleString():'Not available')+'. Unpaid amounts are conditional, not guaranteed earnings.</p>'+link(personal.disqualification?.signature,'Disqualifying exit evidence')+table(personal.allocations);
   host.innerHTML+='<div class="live-metrics"><div><span>Qualifying tokens</span><strong>'+tokens(p.quantity,p.mintDecimals)+'</strong></div><div><span>Prior paid compensation</span><strong>'+sol(p.chain?.paid)+'</strong></div><div><span>Active conditional reservations</span><strong>'+sol(p.chain?.active)+'</strong></div></div>';
  }else host.innerHTML+='<p>Connect your wallet to see your qualifying holdings and payout evidence.</p>';
  host.querySelectorAll('[data-reward-claim]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const result=await signed(wallet,'claim',{mint:button.dataset.rewardClaim,round:button.dataset.round,index:Number(button.dataset.index)});toast(result.state==='finalized'?'Payment finalized. Refresh for its receipt.':'Fresh delivery check: '+(result.reason||result.state));}catch(e){toast(e.message);}finally{button.disabled=false;}});
  host.insertAdjacentHTML('beforeend','<h3>Round evidence</h3>'+data.rounds.map(r=>'<p><a href="'+endpoint+'?action=round&mint='+esc(mint)+'&round='+esc(r.round_id)+'" target="_blank" rel="noopener noreferrer">Round '+esc(r.round_id)+' manifest ↗</a> · '+esc(r.state)+' · '+esc((r.reason||'').replaceAll('_',' '))+'</p>').join(''));
 }catch(e){if(!signal?.aborted&&host.isConnected)host.innerHTML='<h2>Rewards service unavailable</h2><p>'+esc(e.message)+'</p>'+policy;}
}
window.ReboundRewards={mount};
